[dataset]
drop_last = True
seq_len= 90
batch_size = 128
num_workers = 4
feature_num = 13
num_targets = 10
; Hz
raw_sampling_rate = 13230
multi_sampling_rates = [[2205,2205,2205,2205,2205,2205],[735,735,735,735],[441,441,441]]
;multi_sampling_rates = [[4410, 4410, 4410, 4410, 4410, 4410], [1470, 1470, 1470, 1470], [882, 882, 882]]
task = classification

[model]
multi_rate_groups = 3
;mean,cat,
pooling_type = mean
d_model = 32,48,48
kernel_size = 3,1,1
layers_per_encoder = 4
attn_heads = 4
d_ffn = 256
dropout = 0.2
enable_res_parameter = 1
; momentum rate
momentum = 0.99
;loss
lambda = 1,0.3,0.1

[training]
; which device for training, cpu/cuda
device= cuda:0
; learning rate
lr = 0.003
; weight decay used in optimizer
weight_decay = 0
; max num of training epochs
epochs = 100
; max num of pre_training epochs
num_epoch_pretrain = 100
; what type of optimizer to use, adam/adamw
optimizer_type = adamw

beta = 0.2,1